### ISSUE TITLE
videoController is not initializing on iOS web

### ISSUE THREAD

**Issue by yuhao-nyc** [brianegan/chewie#415] opened 2021-01-09 00:58 UTC
<img width="755" alt="Screenshot 2021-01-08 at 7 58 31 PM" src="https://user-images.githubusercontent.com/4121735/104078417-e3721100-51eb-11eb-8f7f-182f3c96e0c3.png">

**Comment by nstrelow** [comment] 2021-01-09 12:16
What is iOS web?

Please add more information, such as flutter doctor, complete error log and example code.

**Comment by yuhao-nyc** [comment] 2021-01-10 16:30
@nstrelow flutter doctor:
```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
I just used the example code here: https://github.com/brianegan/chewie/blob/master/example/lib/main.dart

**Comment by yuhao-nyc** [comment] 2021-01-10 16:31
@nstrelow iOS web meant. when i built this app in Flutter web and use a real device to access it. The video just don't show. It seems related to this error I post above. The `chewieController.videoController` was never intiated.

**Comment by nstrelow** [comment] 2021-01-10 16:37
Can you provide an example project?

**Comment by yuhao-nyc** [comment] 2021-01-10 21:08
```
class _ExampleState extends ExampleState<Example> {
  VideoPlayerController _videoPlayerController;
  ChewieController _chewieController;

  @override
  initState() {
    super.initState();
  }

  @override
  void dispose() {
    _videoPlayerController?.dispose();
    _chewieController?.dispose();
    super.dispose();
  }

  Future<void> initializePlayer() async {
    _videoPlayerController = VideoPlayerController.network(
        'https://videoSrc.com');
    await _videoPlayerController.initialize();
    _chewieController = ChewieController(
      videoPlayerController: _videoPlayerController,
      autoPlay: true,
      allowedScreenSleep: false,
      allowFullScreen: false,
      aspectRatio: 16 / 9,
      allowPlaybackSpeedChanging: false,
      showControlsOnInitialize: false,
    );
    // needed to initialize the video player
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Center(
                                      child: _chewieController != null &&
                                              _chewieController
                                                  .videoPlayerController
                                                  .value
                                                  .initialized
                                          ? Chewie(
                                              controller: _chewieController,
                                            )
                                          : Container(
                                              alignment: Alignment.center,
                                              child:
                                                  CircularProgressIndicator(),
                                            )),);
  }

```

**Comment by yuhao-nyc** [comment] 2021-01-10 21:09
that's the related code. I didnt really add anything special to it. But the video just not load in iOS devices (flutter web build in Safari)

**Comment by Ahmadre** [comment] 2021-01-21 00:26
> that's the related code. I didnt really add anything special to it. But the video just not load in iOS devices (flutter web build in Safari)

The problem is: you're not initialising correctly. You have to wait for the videoplayerController to initialize and not the chewieController (see your build method).

**Comment by yuhao-nyc** [comment] 2021-01-22 17:08
I simply followed this example https://github.com/brianegan/chewie/blob/master/example/lib/main.dart

Also tried out using `videoController.value.initialized` instead of `_chewieController != null && _chewieController.videoPlayerController.value.initialized`. 

Got this error ```invalid member on null: 'value'```

**Comment by yuan9034** [comment] 2021-04-20 02:05
I have the same problem

**Comment by QJJMSK** [comment] 2021-06-08 02:53
hello,boy,have you fixed it? and  I have same problem

**Comment by nstrelow** [comment] 2021-07-26 11:44
Will close, as this should be fixed by video_player_web.

Reopen if it is still happening.

**Closed by nstrelow** 2021-07-26 11:44 UTC
