### ISSUE TITLE
Exit fullscreen does not call Navigator pop (stays open)

### ISSUE THREAD

**Issue by besserwisser** [brianegan/chewie#184] opened 2019-08-05 07:39 UTC
chewie version: 0.9.7
main testing ios: android

Pressing the fullscreen button does not close the fullscreen! 

The isse is in the ChewieState:

```
@override
  void dispose() {
    widget.controller.removeListener(listener);
    super.dispose();
  }

[...]

  void listener() async {
    if (widget.controller.isFullScreen && !_isFullScreen) {
      _isFullScreen = true;
      await _pushFullScreenWidget(context);
    } else if (_isFullScreen) {
      Navigator.of(context).pop(); // not called
      _isFullScreen = false;       // not called
    }
  }
```

I checked with prints that the listener and therefore Navigator.of(context).pop() is usually not called, because the listener is removed by the dispose method already. 

What worked for me is the remove the "else if" statement from the code snippit above. And instead put the pop logic in the _MaterialControlsState class in the following function: 

```
  void _onExpandCollapse() {
    setState(() {
      _hideStuff = true;

      chewieController.toggleFullScreen();
      if(!chewieController.isFullScreen)   // new
        Navigator.of(context).pop();       // new
      _showAfterExpandCollapseTimer = Timer(Duration(milliseconds: 300), () {
        setState(() {
          _cancelAndRestartTimer();
        });
      });
    });
  }
```

I am new to flutter and chewie, so I am not feeling comfortable to create a pull request. Can you please check on this issue (also the iOS side?) and fix it in a release?

**Comment by cbenhagen** [comment] 2019-09-02 20:35
Can't reproduce the issue here. Can you please provide a non working example?

**Comment by cbenhagen** [comment] 2019-12-22 16:20
Without further info we can't do anything about this issue. I am therefore closing it. Please add details if you think this should be reopened.

**Closed by cbenhagen** 2019-12-22 16:20 UTC
Labels: awaiting feedback
