### ISSUE TITLE
Subtitles (CC)

### ISSUE THREAD

**Issue by fanfantasi** [brianegan/chewie#162] opened 2019-05-26 19:59 UTC
Read file .srt subtitle video streaming, how show subtitle in video streaming.. Please help me?...

**Comment by rakyat-game** [comment] 2019-06-25 10:58
Duplicate issue, please read #77

**Comment by snaeji** [comment] 2019-06-26 17:06
You should be able to use this:

https://github.com/snaeji/video_player-0.10.1-3
https://github.com/snaeji/chewie-0.9.7

**Comment by fanfantasi** [comment] 2019-06-26 17:17
Thanks ya

Pada tanggal Kam, 27 Jun 2019 00.06, snaeji <notifications@github.com>
menulis:

**Comment by cbenhagen** [comment] 2019-09-02 22:32
Duplicate of #77

**Closed by cbenhagen** 2019-09-02 22:32 UTC
